/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Help.java
 *
 * Created on Mar 25, 2010, 11:30:43 AM
 */

/**
 *
 * @author Big Tim
 */
public class GraphDrawHelp extends javax.swing.JFrame {

    /** Creates new form Help */
    public GraphDrawHelp() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
	jLabel2 = new javax.swing.JLabel();
	jLabel3 = new javax.swing.JLabel();
	jLabel4 = new javax.swing.JLabel();
	jLabel5 = new javax.swing.JLabel();
	jLabel6 = new javax.swing.JLabel();
	jLabel7 = new javax.swing.JLabel();
	jLabel8 = new javax.swing.JLabel();
	jLabel9 = new javax.swing.JLabel();
	jLabel10 = new javax.swing.JLabel();
	jLabel11 = new javax.swing.JLabel();
	jLabel12 = new javax.swing.JLabel();
	jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusableWindowState(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 416, 76, -1));


        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); 
        jLabel1.setText("Graph Draw"); 
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 19, -1, 36));

	jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); 
        jLabel2.setText("The abstract definition of a graph hides the picture one normally "); 
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 100, -1, 36));

	jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); 
        jLabel3.setText("associates with a graph. DRAW takes the input file given and draws"); 
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 115, -1, 36));

	jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); 
        jLabel4.setText("the graph. The vertices are equally spaced around a circle and all"); 
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 130, -1, 36));
	
	jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); 
        jLabel5.setText("edges are drawn either on the boundary of the circular region or"); 
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 145, -1, 36));

	jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); 
	jLabel6.setText("interior to the circle. No attempt is made to optimize the drawing"); 
	getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 160, -1, 36));

	jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); 
        jLabel7.setText("in this case. For example, one could want the vertices to be displayed"); 
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 175, -1, 36));

	jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); 
        jLabel8.setText("in some order, but here the numbering around the circle corresponds"); 
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 190, -1, 36));

	jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); 
        jLabel9.setText("to the original labelling of the vertices given in the input file."); 
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 205, -1, 36));

	jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); 
	jLabel10.setText("Later developments of GraphWorks II will deal with options for"); 
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 235, -1, 36));

	jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); 
	jLabel11.setText("the display of a graph. Currently, a graph will be drawn as"); 
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 250, -1, 36));
	
	jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); 
	jLabel12.setText("part of the display for each of the options."); 
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 265, -1, 36));




        pack();
   }

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {
	MainMenu mm = new MainMenu();
	mm.setLocationRelativeTo( null );
	mm.setVisible(true);
	this.setVisible(false);
	this.dispose();
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphDrawHelp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;  
    private javax.swing.JScrollPane jScrollPane1;
}
